pipeline {
    agent any

    environment {
        DOCKER_CREDENTIALS_ID='docker-hub-credentials'
        DOCKER_REPO='erickalandev/produto_service_repository'
    }

    stages {
        stage('Checkout') {
            steps {
                // Verificar o código do repositório
                checkout scm
            }
        }

        stage('Set Permissions') {
            steps {
                dir('Backend/produto-service') {
                    sh 'chmod +x mvnw || true' //ignora erros caso não consiga mudar a permissão
                    sh 'ls -la' //verificando se o arquivo e diretorio estão presentes
                    sh 'ls -la .mvn/wrapper' // aqui ele especifica o diretorio
                }
            }
        }

        stage('Build Produto-Service') {
            steps {
                dir('Backend/produto-service') {
                    // Comandos para construir o micro serviço Java 
                    sh './mvnw clean package'
                }
            }
        }

        stage('Test Produto-Service') {
            steps {
                dir('Backend/produto-service') {
                    // Comando para realizar os testes
                    sh './mvnw test'
                }
            }
        }

        stage('Docker Build') {
            steps {
                script {
                    // Muda para o diretório onde o Dockerfile está
                    dir('Backend/produto-service') {
                        // Build da imagem Docker do micro serviço
                        sh 'docker build -t $DOCKER_REPO:latest .'
                        
                        docker.withRegistry('', DOCKER_CREDENTIALS_ID) {
                            // Push da imagem para um repositório de imagens (como docker hub ou AWS ECR)
                            sh 'docker push $DOCKER_REPO:latest'
                        }
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                // Comando para realizar o deploy, por exemplo, rodando um container ou usando o kubernates
                sh 'docker-compose up -d'
            }
        }
    }
}